# Workspace subgroup

Generated map of this subgroup: its directory structure, each repo's purpose
inlined, child subgroups inlined recursively. Regenerated by the `workspace`
repo's clone-and-index bootstrap. See [workspace](https://gitlab.com/konradodwrot/workspace).

@assets/data/repo-index.md
