#!/bin/zsh
#>[what]
#   generate each subgroup's repo-index + rendered AGENTS.md/CLAUDE.md under
#   $WORKSPACE_DIR/$HOST_DIR_GITLAB_GROUP (whole $WORKSPACE_DIR if the host dir is unset)
#/[what]

emulate -LR zsh
setopt errexit pipefail
umask 002

##[>] 🤖🤖🤖
#[why] environments without the render-files toolchain (image bakes) skip
if ! (( $+commands[render-repo-group-index] )) {
  print -r -- "index: skip: render-repo-group-index not found"
  return 0
}

#[why] gate on the same vars as 10-clone: no token/group -> the clone was skipped, so there is no group tree to index
typeset v
for v in GITLAB_TOKEN GITLAB_GROUP; do
  if [[ -z ${(P)v-} ]] {
    print -r -- "index: skip: $v unset"
    return 0
  }
done

typeset root=${WORKSPACE_DIR:-$HOME/projects/gitlab}
#[what] scope the walk to the cloned group's host dir when set
if [[ -n ${HOST_DIR_GITLAB_GROUP-} ]] root=${root}/${HOST_DIR_GITLAB_GROUP}
typeset repo_root=$(git -C ${0:A:h} rev-parse --show-toplevel)
typeset tpl=${repo_root}/templates/3-audience/subgroup-index.md.ontoRepo.tpl

#[what] a subgroup is any dir under $root with >=1 repo (.git) at any depth below.
#   render-repo-group-index owns discovery; here we drive one binary per subgroup.
function has_repo_below {
  local hits=($1/.git(N/) $1/**/.git(N/))
  (( $#hits ))
}

#[what] inline '@assets/data/repo-index.md' as the file's contents; pass other lines through
function inline_index {
  local dir=$1 body=$2
  print -r -- $body | while IFS= read -r line; do
    if [[ $line == '@assets/data/repo-index.md' ]]; then
      cat ${dir}/assets/data/repo-index.md
    else
      print -r -- $line
    fi
  done
}

function index_subgroup {
  local dir=$1
  local data=${dir}/assets/data
  local hdr="<!-- autogenerated using templates/3-audience/subgroup-index.md.ontoRepo.tpl -->"
  mkdir -p $data
  #[what] repo-index.md: this subgroup's direct children (repos inlined, child subgroups linked)
  render-repo-group-index $dir > ${data}/repo-index.md
  #[what] render the subgroup template (cwd = dir so readBody/@ resolve there)
  local body=$( cd $dir && render-tpl -f $tpl )
  #[what] CLAUDE.md keeps the @-include; AGENTS.md inlines it
  print -r -- $hdr > ${dir}/CLAUDE.md
  print -r -- $body >> ${dir}/CLAUDE.md
  print -r -- $hdr > ${dir}/AGENTS.md
  inline_index $dir $body >> ${dir}/AGENTS.md
  print -r -- "index: $dir"
}

#[what] walk dirs under $root; a subgroup dir is one that is not itself a repo but has a repo below.
#   descend into subgroups (they may nest); stop at repos (walk returns before indexing them).
function walk {
  local dir=$1
  [[ -d $dir/.git ]] && return 0
  local child had=0
  for child in $dir/*(N/); do
    if { has_repo_below $child } { had=1; walk $child }
  done
  (( had )) && index_subgroup $dir
}

walk $root
##[<] 🤖🤖🤖
